# Disable minio the default
minio:
  enabled: false
 
# Enable gcs
gcs:
  enabled: true
  project: REPLACE_ME
  jsonKey: '<SERVICE_ACCOUNT_JSON>'
 
# Name has to be unique in GCS.
storageBucket: REPLACE_ME-spinnaker-TIMESTAMP 
 
# Configure your Docker registries here
accounts:
- name: gcr
  address: https://gcr.io
  username: _json_key
  password: '<SERVICE_ACCOUNT_JSON>'
  email: 1234@5678.com
